name: branch-master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: setup:checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: setup:cache:node
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/.yarn/install-state.gz
            ${{ github.workspace }}/.nxcache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: test:lint
        shell: bash
        run: |
          yarn reset
          yarn lint
      - name: build:prod
        shell: bash
        run: |
          yarn build
      - name: test:unit
        shell: bash
        run: |
          yarn test
          yarn merge-reports
      - name: test:coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/report/lcov.info
      - name: build:upload:artifacts
        if: github.base_ref == 0
        uses: actions/upload-artifact@v3
        with:
          name: ngrx-firebase-${{ github.sha }}
          path: ${{ github.workspace }}/dist/packages
